apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deploy
  labels:
    app: go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      name: go-app-pod
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app-container
          image: asilbek5999/go-app:v2
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: info 
                  key: env
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: info 
                  key: log_leveI
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: info 
                  key: grpc_port
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: db-secret 
                  key: DB_URI
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP 
